version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell

formatters:
  enable:
    - gofmt

run:
  timeout: 5m

issues:
  uniq-by-line: true