run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gosec
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false

issues:
  exclude-use-default: false
  exclude:
    - "should have comment"