services:
  dokkee-postgres:
    image: postgres:18.1-bookworm
    container_name: dokkee-env-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql
    restart: always

  dokkee-backend:
    build:
      context: .
      args:
        - PORT=${PORT:-8000}
    container_name: dokkee-env-backend
    environment:
      - POSTGRES_HOST=dokkee-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - salt=${salt}
      - sign_key=${sign_key}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    depends_on:
      - dokkee-postgres
    restart: always

  dokkee-postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations
  
  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: dokkee-postgres-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:dokkee-postgres:5432
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"